### ISSUE TITLE
Large mesh rendering crash

### ISSUE THREAD

**Issue by Taiyuan-Zhang** [HTDerekLiu/BlenderToolbox#20]
I can't find a version of Blender 4.0.0. When using Blender 4.0.2 or 3.6, the rendering process will occupy 100% hard disk and then crash without any error or warning. Mesh of small size like spot.obj can be rendered, but a little bit larger model like armadillo crashes. It seems like it gets stuck at the set shading stage.

**Comment by HTDerekLiu** [comment]
Which material were you using? Some functions (e.g., `drawEdgeSubset`) will take a long time if you have too many edges because it is simply a for loop over them and then duplicate a mesh for each edge. But most functions should be fine, for instance, here is my simple test of the plastic material on an armadillo with 80K faces. 
![demo_plastic](https://github.com/HTDerekLiu/BlenderToolbox/assets/32198009/20664a93-b14b-4ce9-825c-015503b23575)

If there is a specific effect you hope to create, perhaps there is an alternative scalable way to achieve something similar.

**Comment by HTDerekLiu** [comment]
I just updated the `drawEdgeSubset` function and now it should be faster, if that is the one you are using. Currently the change is only on the repo, not in the version in pip yet. So you will have to use the old way: executing it by calling `blender -b -P XXX.py` for now. Hope that can solve your problem!
